<!DOCTYPE html>
<html lang="fr">
<head>
		<meta charset="utf-8">
        <link rel="stylesheet" href="stylecv.css"/>
</head>
<body>
    <header>
        <h1>NOM PR&Eacute;NOM</h1>
        <h2>Intitulé du poste</h2>
    </header>
    <section class="info">
        <h3>INFORMATIONS</h3>
        <h4>Contact</h4>
        <h5>Email</h5>
            <p>email@example.com</p>   
        <h5>Téléphone</h5>
            <p>01 02 03 04 05</p>
        <h5>Linkedin</h5>
            <p><a href="https://fr.linkedin.com/"></a></p>
        <h5>GitHub</h5>
            <p><a href="https://github.com/"></a></p>
        <h4>Biographie</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vulputate arcu quis enim imperdiet, ut efficitur erat dapibus. Integer eu ligula mattis, iaculis augue ac, vestibulum nisi. Aliquam efficitur sit amet lectus ac mattis. Praesent scelerisque pharetra nulla, in laoreet massa gravida eu. Aenean dignissim suscipit nulla, non porttitor ipsum commodo vitae. Donec orci orci, imperdiet mollis finibus in, porttitor vel urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque bibendum laoreet leo vel eleifend. Mauris eget porttitor leo, eu venenatis est. Fusce vitae fringilla ante, ac faucibus arcu. Nunc cursus eget risus non molestie. Vivamus condimentum euismod ante nec vulputate. Etiam commodo bibendum diam nec lobortis.</p>
        <h4>Loisirs</h4>
            <ul>
                <li>Jeux de stratégie</li>
                <li>Violon</li>
                <li>Roller Derby</li>
                <li>Voile</li>
            </ul>
    </section>
    <section class="skills">
        <h3>COMP&Eacute;TENCE</h3>
        <h4>Langages de programmation</h4>
            <ul>
                <li>HTML</li>
                <li>CSS</li>
                <li>Javascript</li>
                <li>PHP</li>
                <li>SQL</li>
            </ul>
        <h4>Frameworks & Librairies</h4>
            <ul>
                <li>Sass</li>
                <li>Bootstrap</li>
                <li>Symfony</li>
                <li>Laravel</li>
            </ul>
        <h4>Logiciels</h4>
            <ul>
                <li>Photoshop</li>
                <li>Illustrator</li>
                <li>XD</li>
                <li>Figma</li>
            </ul>
        <h4>Langues</h4>
            <ul>
                <li>Anglais</li>
                <li>Francais</li>
                <li>Arabe</li>
            </ul>
    </section>
</body>
</html>