<!DOCTYPE html>
<html lang="fr">
<head>
		<meta charset="utf-8">
        <link rel="stylesheet" href="style.css"/>
</head>
<body>
<div class="container">
    <section class="info">
       <h2>INFORMATIONS</h2>
       <form class="form">
           <fieldset>
    <label class="desc" id="name" for="Field1">Nom</label>
    <input id="name" name="name" type="text" value="">
           </fieldset>
           <fieldset>
    <label class="desc" id="firstname" for="Field3">Prénom</label>
     <input id="firstname" name="firstname" type="text"> 
            </fieldset>
            <fieldset>
    <label class="desc" id="title1" for="Field1">Email</label>
      <input id="Email" name="Email" type="text" class="text">
            </fieldset>
            <fieldset>
    <label class="desc" id="phone" for="phone">Téléphone</label>
        <input id="phone" name="phone" type="phone" class="text">
            </fieldset>
            <fieldset>
    <label class="linkedin" id="linkedin" for="linkedin">Linkedin</label>
        <input id="linkedin" name="linkedin" type="text" class="text">
            </fieldset>
            <fieldset>
    <label class="github"  for="Github">Github</label>
    <input name="github" type="text" class="text" value="">
            </fieldset>
    <div>
    <label class="bio" for="bio">
      Biographie
    </label>
    <div>
      <textarea name="bio" spellcheck="true" rows="10" cols="50" tabindex="4"></textarea>
    </div>
  </div>
  
    <label class="loisir1"  for="loisir1">Loisir 1</label>
    <input name="loisir1" type="text" class="text">
    
    <label class="loisir2"  for="loisir2">Loisir 2</label>
    <input name="loisir2" type="text" class="text">
    
    <label class="loisir3"  for="loisir3">Loisir 3</label>
    <input name="loisir3" type="text" class="text">
    
    <label class="loisir4"  for="loisir4">Loisir 4</label>
    <input name="loisir4" type="text" class="text">
    
</form>
        <div class="langage"> 
        <h3>Langues</h3>
        <ul>
            <li><input type="checkbox">Francais</li>
            <li><input type="checkbox">Anglais</li>
            <li><input type="checkbox">Arabe</li>
            <li><input type="checkbox">Breton</li>
            <li><input type="checkbox">Espagnol</li>
        </ul>
        </div>
        <button class="btn" type="button">ENVOYER</button>
    </section>
    <section class="skills">
        <h2>COMP&Eacute;TENCES</h2>
        <h3>Languages de programmation</h3>
        <ul>
            <li><input type="checkbox">Html</li>
            <li><input type="checkbox">CSS</li>
            <li><input type="checkbox">Javascript</li>
            <li><input type="checkbox">PHP</li>
            <li><input type="checkbox">SQL</li>
        </ul>
        <h3>Frameworks & Librairies</h3>
        <ul>
        <li><input type="checkbox">Sass</li>
        <li><input type="checkbox">Bootstrap</li>
        <li><input type="checkbox">Symfony</li>
        <li><input type="checkbox">Laravel</li>
        </ul>
        <h3>Logiciels</h3>
        <ul>
            <li><input type="checkbox">Photoshop</li>
            <li><input type="checkbox">Illustrator</li>
            <li><input type="checkbox">XD</li>
            <li><input type="checkbox">Figma</li>
        </ul>
        <h3>Couleur du CV</h3>
        <label class="color" for="Couleur">Couleur</label>
        <select>
            <option value="blue">Blue</option>
            <option value="Red">Red</option>
            <option value="Green">Green</option>
            <option value="Yellow">Yellow</option>
        </select>
    </section>
</div>
</body>
</html>